version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    env_file:
      - ./docker-env/.env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod
    links:
      - postgres
    ports:
      - 5000:5000

  postgres:
    container_name: database
    image: postgres
    restart: on-failure
    env_file:
      - ./docker-env/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5430:5430
    volumes:
      - category_task:/var/lib/postgresql/data

volumes:
  category_task:
